// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKCYz3FSaD5MvFIIxaadg9322iaGVmJQw',
    appId: '1:182181283386:web:2904c0b2dcf7fa13431703',
    messagingSenderId: '182181283386',
    projectId: 'finalagain-ce423',
    authDomain: 'finalagain-ce423.firebaseapp.com',
    storageBucket: 'finalagain-ce423.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCugoLKu_2gf5DtM4NWqLvU1ZtYGjAxMew',
    appId: '1:182181283386:android:a24a37c55871b3bb431703',
    messagingSenderId: '182181283386',
    projectId: 'finalagain-ce423',
    storageBucket: 'finalagain-ce423.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO_cHTdEqTQoDs8-_zurztNWyED6f-i5U',
    appId: '1:182181283386:ios:4b8ce36dcc4fd913431703',
    messagingSenderId: '182181283386',
    projectId: 'finalagain-ce423',
    storageBucket: 'finalagain-ce423.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO_cHTdEqTQoDs8-_zurztNWyED6f-i5U',
    appId: '1:182181283386:ios:910f431bba4f5553431703',
    messagingSenderId: '182181283386',
    projectId: 'finalagain-ce423',
    storageBucket: 'finalagain-ce423.appspot.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
